### ISSUE TITLE
How's this fork's mileage on TFS 2015?

### ISSUE THREAD

**Issue by JasonKleban** [pmiossec/TotalTfsMigrationTool#4]
Awesome!  How's this fork's mileage on TFS 2015?

**Comment by pmiossec** [comment]
I don't remember the version of TFS that I had the last time I used it. But I think it was 2015 (maybe Update 1).

I have updated the tfs nuget packages so it should not be a problem...

Feel free also to have a look at a fork that seems to improve some things:
https://github.com/bertvansteen/TotalTfsMigrationTool
