### ISSUE TITLE
Work Item Migration Failed : TF237165

### ISSUE THREAD

**Issue by hdesouky** [pmiossec/TotalTfsMigrationTool#5]
First thanks for the amazing update.

When i tried to migrate workitems for TFS 2013.4 from one project to another it fails while migrating workitem with following error: 

TF237165: Team Foundation could not update the work item because of a validation error on the server. This may happen because the work item type has been modified or destroyed, or you do not have permission to update the work item.

Any thoughts?

**Comment by pmiossec** [comment]
This tool try to create new work items identic to the existing ones. If one
parameters, type, etc is no more a valid or existing one, or you don't have
some rights to create it, it fails to create. Some values that TFS keeps
for history can't be used anymore :-(

That's one of the weakness of this tool!

You have to dig in the code to catch this error (one or more work items
won't be created nor associated but that's the only solution... ) and
prevent the migration to fail.

I think I have a branch that handle this case, but I'm not sure and I can't
verify for you (Internet access limited on holidays....)

Good luck!

**Comment by hdesouky** [comment]
Thanks @pmiossec 
actually i debugged the code the error and validation result didn't reveal any useful information
Amazing this happen for the first workitem :)

Any thoughts about how to find the root cause?

**Comment by hdesouky** [comment]
@pmiossec I succeeded in the migration by following the [https://vosseburchttechblog.azurewebsites.net/index.php/2013/09/01/editing-changed-by-and-changed-date-fields-using-the-tfs-api/](article)

However after migration i found that the story board entries are not created for migrated work items.

I will fix this and create a pull request to you to apply in your main branch if you like

**Comment by pmiossec** [comment]
Great for the pull request!
Thanks.

**Comment by pmiossec** [comment]
merged
